"""update workday add length for list day_of_week

Revision ID: 047de79598d7
Revises: 9aaecfe078bc
Create Date: 2025-12-19 11:02:34.910592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '047de79598d7'
down_revision: Union[str, Sequence[str], None] = '9aaecfe078bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('masterrequest', 'specializations',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=sa.ARRAY(sa.Integer()),
               existing_nullable=False,
               postgresql_using="specializations::integer[]")
    op.alter_column('masterspecialization', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('timetable', 'day_of_week',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.ARRAY(sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekdayenum', native_enum=False, length=15)),
               existing_nullable=False,
               postgresql_using="ARRAY[day_of_week]::varchar(15)[]")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timetable', 'day_of_week',
               existing_type=sa.ARRAY(sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekdayenum', native_enum=False, length=15)),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('masterspecialization', 'name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('masterrequest', 'specializations',
               existing_type=sa.ARRAY(sa.Integer()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    # ### end Alembic commands ###
