"""init

Revision ID: 609f0601a1ec
Revises:
Create Date: 2025-12-01 17:33:48.996294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "609f0601a1ec"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "FACE",
                "HAIR",
                "NAILS",
                "LASH",
                "BROWS",
                "DEPILATION",
                name="categoryenum",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "MASTER", "CLIENT", name="userroleenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone"),
    )
    op.create_table(
        "master",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_rating",
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id_user"),
    )
    op.create_table(
        "dayoff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_master", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id_master"], ["master.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reception",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("id_master", sa.Integer(), nullable=False),
        sa.Column("id_service", sa.Integer(), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED_BY_CLIENT",
                "CANCELLED_BY_MASTER",
                "NO_SHOW",
                "RESCHEDULED",
                "AWAITING_PAYMENT",
                "REFUNDED",
                name="receptionstatusenum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id_master"],
            ["master.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_service"],
            ["service.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_master", sa.Integer(), nullable=False),
        sa.Column("id_user", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["id_master"], ["master.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id_user"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specialization_master",
        sa.Column("id_master", sa.Integer(), nullable=False),
        sa.Column("id_service", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id_master"], ["master.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id_service"], ["service.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_master"),
    )
    op.create_table(
        "timetable",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_master", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.String(length=10), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.ForeignKeyConstraint(["id_master"], ["master.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("timetable")
    op.drop_table("specialization_master")
    op.drop_table("reviews")
    op.drop_table("reception")
    op.drop_table("dayoff")
    op.drop_table("user_rating")
    op.drop_table("master")
    op.drop_table("users")
    op.drop_table("service")
    # ### end Alembic commands ###
