"""delete user in client SET NULL

Revision ID: 47375babb12b
Revises: 94e589ba24ba
Create Date: 2025-12-24 15:32:13.482212

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '47375babb12b'
down_revision: Union[str, Sequence[str], None] = '94e589ba24ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('client_id_user_fkey'), 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'users', ['id_user'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key(op.f('client_id_user_fkey'), 'client', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
