"""init

Revision ID: 94e589ba24ba
Revises: 
Create Date: 2025-12-24 12:45:38.024891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e589ba24ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('masterspecialization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('FACE', 'HAIR', 'NAILS', 'LASH', 'BROWS', 'DEPILATION', name='categoryenum', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MASTER', 'CLIENT', 'ADMINISTRATOR', name='userroleenum', native_enum=False, length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('masterrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('bio_short', sa.String(length=50), nullable=False),
    sa.Column('specializations', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('portfolio', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', name='masterrequeststatusenum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user')
    )
    op.create_table('specialization_service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('masterspecialization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['masterspecialization_id'], ['masterspecialization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('service_id', 'masterspecialization_id')
    )
    op.create_table('MasterServiceUnique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_master', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_master'], ['master.id'], ),
    sa.ForeignKeyConstraint(['id_service'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_master', 'id_service')
    )
    op.create_table('client_rating',
    sa.Column('id_from', sa.Integer(), nullable=False),
    sa.Column('id_to', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_example_value_ranges_1_5'),
    sa.ForeignKeyConstraint(['id_from'], ['master.id'], ),
    sa.ForeignKeyConstraint(['id_to'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id_from', 'id_to')
    )
    op.create_table('dayoff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_master', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_master'], ['master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_rating',
    sa.Column('id_from', sa.Integer(), nullable=False),
    sa.Column('id_to', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_example_value_range_1_5'),
    sa.ForeignKeyConstraint(['id_from'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_to'], ['master.id'], ),
    sa.PrimaryKeyConstraint('id_from', 'id_to')
    )
    op.create_table('reception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('id_master', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED_BY_CLIENT', 'CANCELLED_BY_MASTER', 'NO_SHOW', 'RESCHEDULED', 'AWAITING_PAYMENT', 'REFUNDED', name='receptionstatusenum', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_master'], ['master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_service'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_master', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_master'], ['master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialization_master',
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('masterspecialization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['masterspecialization_id'], ['masterspecialization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('master_id', 'masterspecialization_id')
    )
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_master', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.ARRAY(sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', name='weekdayenum', native_enum=False, length=15)), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_master'], ['master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_master', 'day_of_week', name='uq_master_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    op.drop_table('specialization_master')
    op.drop_table('reviews')
    op.drop_table('reception')
    op.drop_table('master_rating')
    op.drop_table('dayoff')
    op.drop_table('client_rating')
    op.drop_table('MasterServiceUnique')
    op.drop_table('specialization_service')
    op.drop_table('masterrequest')
    op.drop_table('master')
    op.drop_table('client')
    op.drop_table('users')
    op.drop_table('service')
    op.drop_table('masterspecialization')
    # ### end Alembic commands ###
