"""fix enum for string

Revision ID: 5916ba340467
Revises: 609f0601a1ec
Create Date: 2025-12-09 23:44:48.931308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5916ba340467'
down_revision: Union[str, Sequence[str], None] = '609f0601a1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reception', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED_BY_CLIENT', 'CANCELLED_BY_MASTER', 'NO_SHOW', 'RESCHEDULED', 'AWAITING_PAYMENT', 'REFUNDED', name='receptionstatusenum'),
               type_=sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED_BY_CLIENT', 'CANCELLED_BY_MASTER', 'NO_SHOW', 'RESCHEDULED', 'AWAITING_PAYMENT', 'REFUNDED', name='receptionstatusenum', native_enum=False),
               existing_nullable=False)
    op.alter_column('service', 'category',
               existing_type=postgresql.ENUM('FACE', 'HAIR', 'NAILS', 'LASH', 'BROWS', 'DEPILATION', name='categoryenum'),
               type_=sa.Enum('FACE', 'HAIR', 'NAILS', 'LASH', 'BROWS', 'DEPILATION', name='categoryenum', native_enum=False),
               existing_nullable=False)
    op.add_column('user_rating', sa.Column('id_from', sa.Integer(), nullable=False))
    op.add_column('user_rating', sa.Column('id_to', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_rating_id_user_fkey'), 'user_rating', type_='foreignkey')
    op.create_foreign_key(None, 'user_rating', 'users', ['id_to'], ['id'])
    op.create_foreign_key(None, 'user_rating', 'users', ['id_from'], ['id'])
    op.drop_column('user_rating', 'id_user')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'MASTER', 'CLIENT', name='userroleenum'),
               type_=sa.Enum('ADMIN', 'MASTER', 'CLIENT', name='userroleenum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MASTER', 'CLIENT', name='userroleenum', native_enum=False),
               type_=postgresql.ENUM('ADMIN', 'MASTER', 'CLIENT', name='userroleenum'),
               existing_nullable=False)
    op.add_column('user_rating', sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_rating', type_='foreignkey')
    op.drop_constraint(None, 'user_rating', type_='foreignkey')
    op.create_foreign_key(op.f('user_rating_id_user_fkey'), 'user_rating', 'users', ['id_user'], ['id'])
    op.drop_column('user_rating', 'id_to')
    op.drop_column('user_rating', 'id_from')
    op.alter_column('service', 'category',
               existing_type=sa.Enum('FACE', 'HAIR', 'NAILS', 'LASH', 'BROWS', 'DEPILATION', name='categoryenum', native_enum=False),
               type_=postgresql.ENUM('FACE', 'HAIR', 'NAILS', 'LASH', 'BROWS', 'DEPILATION', name='categoryenum'),
               existing_nullable=False)
    op.alter_column('reception', 'status',
               existing_type=sa.Enum('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED_BY_CLIENT', 'CANCELLED_BY_MASTER', 'NO_SHOW', 'RESCHEDULED', 'AWAITING_PAYMENT', 'REFUNDED', name='receptionstatusenum', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED_BY_CLIENT', 'CANCELLED_BY_MASTER', 'NO_SHOW', 'RESCHEDULED', 'AWAITING_PAYMENT', 'REFUNDED', name='receptionstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
