"""reveiw service model and add specialization

Revision ID: 9aaecfe078bc
Revises: 293f3037e271
Create Date: 2025-12-17 12:18:42.453635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aaecfe078bc'
down_revision: Union[str, Sequence[str], None] = '293f3037e271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MasterServiceUnique',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_master', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_master'], ['master.id'], ),
    sa.ForeignKeyConstraint(['id_service'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_master', 'id_service')
    )
    op.drop_column('service', 'duration_minutes')
    op.drop_column('service', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('service', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('MasterServiceUnique')
    # ### end Alembic commands ###
