"""add for masterrequest model column status

Revision ID: 65da8249b842
Revises: 7409151610c6
Create Date: 2025-12-12 12:34:08.773840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65da8249b842'
down_revision: Union[str, Sequence[str], None] = '7409151610c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masterrequest', sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', name='masterrequeststatusenum', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masterrequest', 'status')
    # ### end Alembic commands ###
