"""fix propery masters in Service model

Revision ID: aaa4cb079062
Revises: 65da8249b842
Create Date: 2025-12-12 15:01:08.670947

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'aaa4cb079062'
down_revision: Union[str, Sequence[str], None] = '65da8249b842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
