"""add array for day_of_week

Revision ID: 270721d86811
Revises: 2650a44f73b0
Create Date: 2025-12-17 17:13:44.757731

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '270721d86811'
down_revision: Union[str, Sequence[str], None] = '2650a44f73b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
