"""add rating for master and client

Revision ID: c107923c6f86
Revises: 76b10c0cb976
Create Date: 2025-12-23 17:55:58.415896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c107923c6f86'
down_revision: Union[str, Sequence[str], None] = '76b10c0cb976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('is_guest', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('client_rating',
    sa.Column('id_from', sa.Integer(), nullable=False),
    sa.Column('id_to', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_example_value_ranges_1_5'),
    sa.ForeignKeyConstraint(['id_from'], ['master.id'], ),
    sa.ForeignKeyConstraint(['id_to'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id_from', 'id_to')
    )
    op.create_table('master_rating',
    sa.Column('id_from', sa.Integer(), nullable=False),
    sa.Column('id_to', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_example_value_range_1_5'),
    sa.ForeignKeyConstraint(['id_from'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_to'], ['master.id'], ),
    sa.PrimaryKeyConstraint('id_from', 'id_to')
    )
    op.drop_table('user_rating')
    op.add_column('master', sa.Column('rating', sa.Float(), nullable=False))
    op.drop_constraint(op.f('reception_id_master_fkey'), 'reception', type_='foreignkey')
    op.create_foreign_key(None, 'reception', 'master', ['id_master'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reception', type_='foreignkey')
    op.create_foreign_key(op.f('reception_id_master_fkey'), 'reception', 'master', ['id_master'], ['id'])
    op.drop_column('master', 'rating')
    op.create_table('user_rating',
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_from', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_to', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_from'], ['users.id'], name=op.f('user_rating_id_from_fkey')),
    sa.ForeignKeyConstraint(['id_to'], ['users.id'], name=op.f('user_rating_id_to_fkey'))
    )
    op.drop_table('master_rating')
    op.drop_table('client_rating')
    op.drop_table('client')
    # ### end Alembic commands ###
