"""fix relationsship

Revision ID: c1c02999ff29
Revises: 5916ba340467
Create Date: 2025-12-10 00:08:47.999282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1c02999ff29"
down_revision: Union[str, Sequence[str], None] = "5916ba340467"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specialization_master", sa.Column("master_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "specialization_master", sa.Column("service_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint(
        op.f("specialization_master_id_service_fkey"),
        "specialization_master",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("specialization_master_id_master_fkey"),
        "specialization_master",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "specialization_master",
        "service",
        ["service_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "specialization_master",
        "master",
        ["master_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("specialization_master", "id_service")
    op.drop_column("specialization_master", "id_master")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specialization_master",
        sa.Column("id_master", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "specialization_master",
        sa.Column("id_service", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "specialization_master", type_="foreignkey")
    op.drop_constraint(None, "specialization_master", type_="foreignkey")
    op.create_foreign_key(
        op.f("specialization_master_id_master_fkey"),
        "specialization_master",
        "master",
        ["id_master"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("specialization_master_id_service_fkey"),
        "specialization_master",
        "service",
        ["id_service"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("specialization_master", "service_id")
    op.drop_column("specialization_master", "master_id")
    # ### end Alembic commands ###
