"""formated MasterRequestModel

Revision ID: 293f3037e271
Revises: aaa4cb079062
Create Date: 2025-12-12 15:46:30.789913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "293f3037e271"
down_revision: Union[str, Sequence[str], None] = "aaa4cb079062"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "masterrequest",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_unique_constraint(None, "masterrequest", ["id_user"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "masterrequest", type_="unique")
    op.drop_column("masterrequest", "created_at")
    # ### end Alembic commands ###
