"""fix length for user role

Revision ID: 76b10c0cb976
Revises: 7825d0d27c32
Create Date: 2025-12-23 15:26:15.702232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b10c0cb976'
down_revision: Union[str, Sequence[str], None] = '7825d0d27c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('ADMIN', 'MASTER', 'CLIENT', 'ADMINISTRATOR', name='userroleenum', native_enum=False, length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'MASTER', 'CLIENT', 'ADMINISTRATOR', name='userroleenum', native_enum=False, length=15),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
