"""add cascade delete for users

Revision ID: 7825d0d27c32
Revises: 047de79598d7
Create Date: 2025-12-22 11:31:03.080348

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7825d0d27c32'
down_revision: Union[str, Sequence[str], None] = '047de79598d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('master_id_user_fkey'), 'master', type_='foreignkey')
    op.create_foreign_key(None, 'master', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('reception_id_user_fkey'), 'reception', type_='foreignkey')
    op.create_foreign_key(None, 'reception', 'users', ['id_user'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reception', type_='foreignkey')
    op.create_foreign_key(op.f('reception_id_user_fkey'), 'reception', 'users', ['id_user'], ['id'])
    op.drop_constraint(None, 'master', type_='foreignkey')
    op.create_foreign_key(op.f('master_id_user_fkey'), 'master', 'users', ['id_user'], ['id'])
    # ### end Alembic commands ###
