"""column image_url refreshed and column address added

Revision ID: cd483bdaa571
Revises: c63ecd63e505
Create Date: 2026-02-04 16:37:06.542372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd483bdaa571'
down_revision: Union[str, Sequence[str], None] = 'c63ecd63e505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('address', sa.String(length=100), nullable=False))
    op.alter_column('salons', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('salons', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('salons', 'address')
    # ### end Alembic commands ###
