"""column id salon for master added

Revision ID: a4a4c370a11c
Revises: 143c07ccadc8
Create Date: 2026-02-16 14:31:37.135815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a4c370a11c'
down_revision: Union[str, Sequence[str], None] = '143c07ccadc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_salon',
    sa.Column('id_master', sa.Integer(), nullable=False),
    sa.Column('id_salon', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_master'], ['master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_salon'], ['salons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_master', 'id_salon')
    )
    op.add_column('masterrequest', sa.Column('id_salons', sa.ARRAY(sa.Integer()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masterrequest', 'id_salons')
    op.drop_table('master_salon')
    # ### end Alembic commands ###
