"""for master model  face image added

Revision ID: 2745ce977e2a
Revises: a4a4c370a11c
Create Date: 2026-02-17 11:49:23.240642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2745ce977e2a'
down_revision: Union[str, Sequence[str], None] = 'a4a4c370a11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master', sa.Column('face_image', sa.String(), server_default='static/masters/front_images/no_image.png', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master', 'face_image')
    # ### end Alembic commands ###
