"""column for portfolio salons added

Revision ID: 143c07ccadc8
Revises: cd483bdaa571
Create Date: 2026-02-06 17:32:29.048622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143c07ccadc8'
down_revision: Union[str, Sequence[str], None] = 'cd483bdaa571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('portfolio_url', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'portfolio_url')
    # ### end Alembic commands ###
